### PR TITLE
Mu 1 nu 1 soap compression

### PR DESCRIPTION
**Pull request by jlparkI**
Hi,

So I've added two feature compression schemes for SOAP features, together with an optional element-specific weighting feature that can be used with these feature compression schemes. As previously discussed (see pull request #114), the level of compression is now specified by supplying a ```"compression"``` option which is a dict and contains the keys / compression options described below:

```
# No compression. Default value. Scales as 1/2*NS(NS+1)(L+1).
compression = "off"
compression = {
    mode: "off"
}

# Compression scheme mu=1, nu=1 explained in https://doi.org/10.1038/s41524-022-00847-y. Scales as N²S(L + 1)
compression = "mu1nu1"
compression = {
    mode: "mu1nu1"
}

# Element-agnostic mu=2 explained in https://doi.org/10.1038/s41524-022-00847-y. Scales as 1/2*N(N+1)(L+1)
compression = "mu2"
compression = {
    mode: "mu2",
    species_weighting: {'H': 0.5, "O": 1}
}

# Compression where cross-species densities are not calculated at all. Corresponds to current setup of crossover=False. Scales as 1/2*NS(N+1)(L+1).
compression = "crossover"
compression = {
    mode: "crossover"
}
```

The crossover option in the SOAP constructor has been removed, since it is now redundant. If there are any issues with these changes or any additional changes you want to make to this feature compression scheme, please let me know. Thanks again!

### CODE REVIEW

**Comment by lauri-codes** [comment]
I will merge this now into v2.1.0 which will be the next version to be released. Thanks again! Is it OK if I give credits to your GitHub username for the implementation of this feature in our changelog?

**Comment by jlparkI** [comment]
That sounds great! yes, it's fine to credit my github username. thanks again.

**Comment by lauri-codes** [comment]
There are a few conflicts: could you take a look when you have time?

**Comment by jlparkI** [comment]
OK, the new commits to the main branch had changed ```rcut```, ```nmax``` and ```lmax``` in ```soap.cpp``` to be ```r_cut```, ```l_max``` and ```n_max```; I have updated this in the mu1 branch for the pull request. Also, ```test_soap.py``` in main had been changed under the ```test_exceptions``` function in the main branch, changing the terminology in some of the exceptions and making sure that the exceptions matched certain wording. I've added these changes to the mu1 branch for the pull request.

Finally, it looks like the docs were probably updated in main,hence the differences between objects.inv, searchindex.js and soap.html. I think that whatever version of searchindex.js and objects.inv is present on the main branch should be preferred.

I've added another commit with these changes. Is that enough to be able to fix the conflicts, or if not, how would you like me to handle this?

**Comment by lauri-codes** [comment]
The contents of .html, .inv, and .js files are autogenerated by sphinx, so the contents don't really matter that much. You can e.g. resolve them in favour of your changes: I will anyways regenerate them. The important files to resolve are the .py and .rst files, which you already seen to have fixed. Just push new commits that resolve the conflicts and all should be good.

**Comment by jlparkI** [comment]
I have added a new commit that fixed all conflicts with base....let me know if there are other problems...thanks.

**Pull request merged**
