### PR TITLE
SOAP feature compression

### PR DESCRIPTION
**Pull request by jlparkI**
Hi,

So I've added two feature compression schemes for SOAP features, together with an optional element-specific weighting feature that can be used with one of these feature compression schemes. The class constructor for SOAP now has the following options:

`compression="off"` -- can also be set to `compression="agnostic"` or `compression="m1n1"`. The former is element-agnostic, i.e. the features are generated in an element-agnostic way (in which case the user may also want to specify element-specific weighting). The latter corresponds to the mu=1, nu=1 [compression scheme from Darby et al.](https://www.nature.com/articles/s41524-022-00847-y), in which case the number of features for a given center will scale linearly rather than quadratically with the number of possible species / elements.

`species_weighting=None` -- can also be a dictionary (in which case it must contain one element for each species / element with an element-specific weight). If the user does supply a dictionary, these weights are used to weight the elements (in addition to any distance-based weighting they have specified). I can't imagine anyone would want to use this unless they're also using the `compression="agnostic"` option, but the code does not currently prohibit them from using it in any scenario where they want to do so. The code does not currently check to make sure that species weights are not set to numbers that might cause problems (e.g. 0, complex numbers, etc.) since presumably the user is unlikely to do this.

To implement these changes, we've made changes to the following files;
descriptors/soap.py
descriptors/descriptor_local.py
ext/SOAPGTO.cpp
ext/SOAPGeneral.cpp
ext/SOAP.cpp
ext/SOAPGTO.h
ext/SOAPGeneral.h
ext/SOAP.h
ext/ext.cpp
ext/descriptor.cpp

and of course to the docs and the tests, specifically test_soap.py and conftest.py. We examine how well these compressed features perform in a quick-and-dirty test on the QM9 repo shown here:

https://github.com/jlparkI/dscribe_qm9_testing

Code has been run through the linter -- if there are any problems with the changes I've implemented, or if you don't think the dscribe repo is the right place for these just let me know. Thanks again!

### CODE REVIEW

**Comment by lauri-codes** [comment]
Hi @jlparkI, thanks for the PR. I'm currently on vacation, but I will come back to this.

**Comment by lauri-codes** [comment]
Hi @jlparkI!

Thanks a lot for all your hard work. This is definitely a very nice feature which will definitely be merged. I do have a few suggestions that we could discuss here:

- I think `compression` could be a dictionary, in the same style as e.g. `weighting` is. Although currently only the element-agnostic compression takes any additional arguments, there might be other compression schemes in the future that take further arguments and thus a dictionary will be more future-proof IMO. This way we can add e.g. compression parameters etc. in the same argument. This makes it also easier for the user to understand their connection. We can also provide the option or compression being only a string, but then compression arguments need some defaults.
- `species_weighting` should then be in the compression dictionary.
- We currently have a parameter called 'crossover', which is actually a type of compression. It should be made into a compression option.

So all in all I would propose having the following compression options (I took inspiration for the names from Table 1 in the article, alternative name suggestions are welcome):

```python
# No compression. Default value. Scales as 1/2*NS(NS+1)(L+1).
compression = None
compression = "nu2"
compression = {
    mode: "nu2"
}

# Compression scheme mu=1, nu=1 explained in https://doi.org/10.1038/s41524-022-00847-y. Scales as N²S(L + 1)
compression = "mu1nu1"
compression = {
    mode: "mu1nu1"
}

# Element-agnostic mu=2 explained in https://doi.org/10.1038/s41524-022-00847-y. Scales as 1/2*N(N+1)(L+1)
compression = "mu2"
compression = {
    mode: "mu2",
    species_weighting: {'H': 0.5, "O": 1}
}

# Compression where cross-species densities are not calculated at all. Corresponds to current setup of crossover=False. Scales as 1/2*NS(N+1)(L+1).
compression = "crossover"
compression = {
    mode: "crossover"
}
```

**Comment by lauri-codes** [comment]
@jlparkI: You have done a very nice work with this! Once we figure out the minor details I think this will be good to go :rocket:

**Comment by jlparkI** [comment]
Hi Lauri,

Thanks -- I think setting this up so that compression is a dictionary makes a lot of sense and I am fine with those naming suggestions. Let me set that up, I'll use the scheme you have in your comment, and then I can submit a new pull request with those additional commits -- probably later this week or early next. For now I will go ahead and close this pull request. Thanks again!

**Pull request closed without merging**
